update_settings:
  name: Update AmbiSense Settings
  description: Update various settings for the AmbiSense LED strip
  target:
    entity:
      domain: light
      integration: ambisense
  fields:
    min_distance:
      name: Minimum Distance
      description: Minimum detection distance for the radar sensor
      example: 30
      selector:
        number:
          min: 0
          max: 200
          unit_of_measurement: cm

    max_distance:
      name: Maximum Distance
      description: Maximum detection distance for the radar sensor
      example: 300
      selector:
        number:
          min: 50
          max: 500
          unit_of_measurement: cm
          
    background_mode:
      name: Background Mode
      description: Enable or disable background lighting
      selector:
        boolean:

    directional_light:
      name: Directional Light
      description: Enable or disable directional light effect
      selector:
        boolean:
      
    brightness:
      name: Brightness
      description: Overall brightness of the LED strip
      example: 150
      selector:
        number:
          min: 0
          max: 255

    light_span:
      name: Light Span
      description: Number of LEDs illuminated in moving light mode
      example: 40
      selector:
        number:
          min: 1
          max: 100

    num_leds:
      name: Number of LEDs
      description: Total number of LEDs in the strip
      example: 300
      selector:
        number:
          min: 1
          max: 2000

    rgb_color:
      name: RGB Color
      description: Set the color of the LED strip using RGB values
      example: [255, 100, 50]
      selector:
        color_rgb:

    light_mode:
      name: Light Mode
      description: Select the operational mode of the LED strip
      example: "Rainbow"
      selector:
        select:
          options:
            - "Standard"
            - "Rainbow"
            - "Color Wave"
            - "Breathing"
            - "Solid"
            - "Comet Trail"
            - "Pulse Waves"
            - "Fire Effect"
            - "Theater Chase"
            - "Dual Scan"
            - "Motion Particles"

    center_shift:
      name: Center Shift
      description: Adjust the center point of the LED effect
      example: 0
      selector:
        number:
          min: -100
          max: 100

    trail_length:
      name: Trail Length
      description: Length of light trails in the effect
      example: 20
      selector:
        number:
          min: 0
          max: 100

    effect_speed:
      name: Effect Speed
      description: Speed of dynamic lighting effects
      example: 50
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    effect_intensity:
      name: Effect Intensity
      description: Intensity of dynamic lighting effects
      example: 75
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    motion_smoothing:
      name: Motion Smoothing
      description: Enable or disable motion smoothing
      selector:
        boolean:

    position_i_gain:
      name: Position I Gain
      description: Integral gain for position control
      example: 0.01
      selector:
        number:
          min: 0
          max: 0.1
          step: 0.001
    
    position_p_gain:
      name: Position P Gain
      description: Proportional gain for position control
      example: 0.1
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
    
    position_smoothing_factor:
      name: Position Smoothing Factor
      description: Smoothing factor for position
      example: 0.2
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
    
    velocity_smoothing_factor:
      name: Velocity Smoothing Factor
      description: Smoothing factor for velocity
      example: 0.1
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
    
    prediction_factor:
      name: Prediction Factor
      description: Factor for predicting future position
      example: 0.5
      selector:
        number:
          min: 0
          max: 1
          step: 0.01

apply_settings:
  name: Apply Settings
  description: Apply all current settings to the device
  target:
    entity:
      domain: light
      integration: ambisense
